name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}

          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            nvm use 24.13.0

            node -v
            npm -v
            pwd

            cd /home/nirmal/Projects/kaamdaar/skilled_nepali_backend

            git fetch origin
            git checkout master
            git reset --hard origin/master
            git clean -fd

            npm ci


            pm2 restart kaamdaar-api